version: '3.7'

services:
  backend:
    build:
      context: ../..  # This should now be the path to the root of your project 'demo'
      dockerfile: tools/docker/Dockerfile.back
    container_name: backend_demo
    ports:
      - "8080:8080"


  frontend:
    build:
      context: ../..  # This should also be the path to the root of your project 'demo'
      dockerfile: tools/docker/Dockerfile.front
    container_name: frontend_demo
    ports:
      - "4200:80"
    # volumes:
    #   - "../../frontend:/app"  # Map your local Angular project directory to the /app directory in the container
    #   - "/app/node_modules"       # Use a volume to keep node_modules persistent and separate from host
    environment:
      - CHOKIDAR_USEPOLLING=true  # This helps with hot reloading on some environments like Windows with Docker Desktop
